### PR TITLE
Kbase 1872 hotfix - public narrative slider

### PR DESCRIPTION
**Pull request by eapearson**
Primarily to ensure that the public narrative slider is indeed public narratives. While in there also fixed a bug with the public narrative slider resetting a search up on the 1/sec refresh. The changes look noisier than they should be because of a retabbing of the file.

### CODE REVIEW

**Comment by briehl** [comment]
Let's get this in so it can be tested on CI

**Comment by eapearson** [comment]
were you suggesting that I merge it? shouldn't that be you?

**Comment by briehl** [comment]
Oops. Closed this tab too soon!

**Comment by briehl** [comment]
Although, really, it shouldn't matter who accepts the PR, as long as other eyes have had a chance to see it, review the code, and discuss what it changes.

**Pull request merged**
