### PR TITLE
WIP: Alleviating testing

### PR DESCRIPTION
**Pull request by briehl**
**READY TO MERGE** :)
This is a work in progress to get some automated testing working. Having this in the form of a PR triggers each commit to get sent to Travis-CI where the tests will happen and coverage gets measured.

There's also a few little fixes in here that doing tests brought up. Funny how that works. :)

### CODE REVIEW

**Comment by briehl** [comment]
Testing works! I also managed to configure Travis-CI to keep a cache of the node modules and bower components, so it should be much faster. Next step: coveralls.

**Comment by eapearson** [comment]
Awesome, do you think it is ready to merge?
I know there will be a couple of conflicts with changes I have coming through since there were fixes that I've already made or files that have been replaced, so if this is ready I can merge, then merge into my branch before I submit a PR with some changes I have for the sample widgets.

**Comment by briehl** [comment]
I'd like to get coveralls working first. This last commit might have done it, or maybe not! Either way, it'll be ready to merge in a little bit.

**Comment by briehl** [comment]
It works! Mostly. The coverage map doesn't seem to track all JS, just the files that are touched in the tests. That might have to do with them only getting loaded by require. Either way, good enough, IMO.

**Pull request merged**
