### PR TITLE
First pass config file improvements

### PR DESCRIPTION
**Pull request by eapearson**
A first pass at improving the config file, and a work in progress, not complete, but does replicate the current config as it exists in ui-common:
- more structure, with consistent naming
- accommodates expansion of properties per service
- merges in config from narrative for ci
- separates config into files by environment (deploys): prod (and dev), ci, next
- now using yaml, because the state of the configs desperately needs internal comments
(we didn't discuss this, I just thought we could try it on for size)
- mass search and replace throughout codebase and reasonable eyeball testing
- the config file used at runtime is located in build/config.yml, and the sources in sources/config/*.yml. This is a suggested directory top level directory layout for source and build.

### CODE REVIEW

**Comment by eapearson** [comment]
Obviously, I forgot to mention the other changes in there. I guess it is too late! There was also a little bit of work to clean up the app startup, which is a bit of a mess and has not been refactored since first put into place to replace angular. I was also trying not to nail that down too early, but it is probably about time to at least use thumbtacks and elmer's.

**Comment by briehl** [comment]
Files changed: 5900!!
What are all those? Removing old dependencies that are now loaded with bower?

**Comment by briehl** [comment]
I notice that not much seems to really work yet (deployed locally with python's SimpleHTTPServer. Is that expected at this stage? I see:
```
2015-07-31T20:34:51.569Z: : main: About to load panels...
2015-07-31T20:34:51.675Z: : main: setting up app
2015-07-31T20:34:51.684Z: : main: running app
ERROR loading panels
The user profile client url is not defined
app is unhappy :(
```

**Comment by briehl** [comment]
Okay, I'm a dummy. missed the README change among the 5900 changed files :)

**Comment by briehl** [comment]
That big pile of file changes was just moving them to a deprecation directory (pending removal all together), and the recent patches fix the dashboard. merging so we can all test things off this branch.

**Pull request merged**
