### PR TITLE
Hotfix so that SDK methods are viewable on man pages

### PR DESCRIPTION
**Pull request by msneddon**
Temporary fix in routing that allows man pages to show SDK module methods

### CODE REVIEW

**Comment by briehl** [comment]
Just noting here that this will need to be fixed in the kbase-ui-plugin-dataview repo as well. @eapearson

**Comment by briehl** [comment]
Er, make that kbase-ui (in the narrativemanager plugin). I'll work on it.

**Comment by briehl** [comment]
@msneddon do you have a working URL example? I'd like to make sure my fix works in the kbase-ui update. (it was really a small fix).

**Comment by msneddon** [comment]
Sure- this url against the CI method store should work with this fix, but didn't before:
/functional-site/#/narrativestore/method/MegaHit/run_megahit

**Pull request merged**
