### PR TITLE
Deployment

### PR DESCRIPTION
**Pull request by briehl**
Added a grunt deploy task and matching deploy.cfg. After running `grunt-build` , run `grunt-deploy` to copy the build artifacts into the configured deployment dir.

Also updated the login flow to go to the dashboard after logging in. Conversely, if not logged in, heading to the dashboard should redirect to the login page.

Todo:
* Add configuration for each deployment environment
* Remove (well, hide, at least) the test menu items while in deployment
* Make post-login redirect configurable
* Make login prompt redirect to last page. E.g., trying to view private data should prompt to login, then redirect back to the data page
* Lots and lots of documentation
* Include build step that generates require config for the Narrative
* Include build step that minifies/compiles some subset of files (though maybe not necessary - need to examine network traffic footprint)
* Adjust tests to work with new directory structure

### CODE REVIEW

**Comment by kkellerlbl** [comment]
Travis failed, is that okay?

**Comment by briehl** [comment]
Yeah, maybe don't accept the PR yet. I'd like to get the tests unbroken first.

**Comment by briehl** [comment]
Added a script under tools (tools/process_config.js) that will process a configuration INI file and build the YAML file that the front end expects. You can run it with:

```
node tools/process_config.js
(defaults to deploy.cfg in ui-common root)
```
or
```
node tools/process_config.js [input config file]
```
or set the `KB_DEPLOYMENT_CONFIG` environment variable and run the script with no inputs

**Comment by briehl** [comment]
At this point, deployment should work with `make && make deploy`, testing should work with `make && make test` (or `grunt build; node tools/process_config.js; grunt deploy`, `grunt test`, respectively).

The grunt stuff could use a little cleanup, especially for running locally, but this should serve the deployment requirement.

**Pull request merged**
