### PR TITLE
Function for genome-set creation was added in NarrativeManager.

### PR DESCRIPTION
**Pull request by rsutormin**

### CODE REVIEW

**Comment by msneddon** [comment]
Just noticed this request- was this meant to pulled into narrative-dev or develop?  Is there any code that calls this new method?

**Comment by briehl** [comment]
Just checking up on this - does it need to go to the search branch or develop?

**Comment by rsutormin** [comment]
I'm not sure it's still necessary. I did for @mlhenderson actually. Matt?

**Comment by mlhenderson** [comment]
Right, this was something I asked Roman to work on that didn't make it into
the Feb deploy.  I think this is useful to have generally, but Bill and I
should discuss this before merging to develop.

**Comment by rsutormin** [comment]
I think (and I remember Mike thought so) it would be better to put it somewhere else. I just didn't find better place when I did this PR (it was Friday evening before code freeze? or close to it).

**Comment by rsutormin** [comment]
I think it's not necessary anymore. So I'll close this PR if there is nobody asking to not do it in an hour.

**Pull request closed without merging**
