### PR TITLE
Fix NAR-697 newlines

### PR DESCRIPTION
**Pull request by briehl**
See https://atlassian.kbase.us/browse/NAR-697 - extra spaces on the ends of lines in the markdown text template were creating undesired line breaks.

This PR also removes (prototype) from the page header, which apparently wasn't pushed in before - see https://atlassian.kbase.us/browse/KBASE-1654

### CODE REVIEW

**Comment by nlharris** [comment]
+1:

**Comment by briehl** [comment]
Note - Travis-CI is going to fail for a while until we get a .travis.yml set up.

**Comment by briehl** [comment]
@eapearson @msneddon would you mind taking a look at this to make sure I followed your scheme right? Thanks!

**Comment by eapearson** [comment]
That text file is designed to be used like this:

../../../tools/markdown-to-js-string.pl < NarrativeManager-welcome-cell-content.txt

to generate the javascript concatenated string, which then is copy/pasted where it needs to be.

Erk.

**Comment by briehl** [comment]
Yup, that's exactly what I did. I just removed the extra spaces in the .txt file, which were generating newlines in the rendered Markdown. Then I ran the script and copy/pasted it into NarrativeManager.js.

**Comment by briehl** [comment]
So, is this the right way to do things? I think we should get this fix in and tested before bugging the devops team for a redeploy.

**Comment by eapearson** [comment]
Do you mean the perl script to prepare the text for for insertion into the javascript?
There are better ways to do it, but I think this method is better than editing the concatenated strings by hand. But that is just my preference.
I'll pull this and test it locally.

**Comment by briehl** [comment]
Thanks Erik!

**Comment by eapearson** [comment]
I don't think I'll have time to get to it today, jammed up with some metrics work, but certainly by some time on Monday.

**Comment by briehl** [comment]
Going ahead and merging this to get it visible on narrative-ci. We can fix problems based on that. I can't wait to get some automated Travis-CI testing working...

**Pull request merged**
