### PR TITLE
Added type browser (for debugging)

### PR DESCRIPTION
**Pull request by eapearson**
Added a type browser panel for debugging. Not quite finished, but want a way to reveal everything the workspace can reveal about a type, to ensure that the type (spec) viewer is behaving well.
Small refactor widget api - create becomes init. There is a "create" method which was a misnomer. It is really used for initializing a widget after it is created.

### CODE REVIEW

**Comment by briehl** [comment]
Is this the replacement for the TypeSpec viewer that was based on the cards?

**Comment by eapearson** [comment]
Yes and no. The "added function spec viewer" is part of the spec viewers (including type and module). The type browser is related, in that it is a simple table view of all types to facilitate testing of the spec viewers (essentially, generating links to all possible spec viewers so that one can click and inspect the state of the widget.) It is not intended as a permanent feature.

**Comment by briehl** [comment]
Is there a link to it I can look at if I were to set up a local server?

**Comment by eapearson** [comment]
it appears in the hamburger menu under "Type Browser" (with the beer mug icon).
screen shot 2015-07-29 at 3 40 50 pm

**Comment by briehl** [comment]
I see. That's pretty cool! Adding it for testing purposes.

**Comment by nlharris** [comment]
Will this be for users or just for developers?

**Comment by eapearson** [comment]
It was set up just for developers, both in the function and form - that is, a need to see and navigate to all types, with no attention to UI other than wrapping in a datatable (a javascript widget we use all over the place, which does give searching and sorting, so it is quite usable.) 
Do you think it would be useful for users?

**Comment by nlharris** [comment]
It could well be useful to a certain subset of power users, but I don't think we need to prioritize that (since it would require extra work fancying the UI and writing documentation). This could be a later goal.
Why is the symbol for the Type Browser a beer stein??

**Comment by eapearson** [comment]
> On Jul 29, 2015, at 4:30 PM, Nomi Harris <notifications@github.com> wrote:
> 
> It could well be useful to a certain subset of power users, but I don't think we need to prioritize that (since it would require extra work fancying the UI and writing documentation). This could be a later goal.
> Why is the symbol for the Type Browser a beer stein??
> 
Just to get a reaction like that!

(Actually, I just wanted a type browser, and grew impatient after scanning the icons page one time, so I just picked one that would need to be replaced, and had the redeeming quality of a chuckle.)

**Comment by cshenry** [comment]
I think the better question is why the beer stein icon is so underused throughout the site... And can we use a shot glass for modeling!?

**Pull request merged**
