### PR TITLE
Catching up ... new demo plugin and doc, moved vis widgets to plugin, file reorg.

### PR DESCRIPTION
**Pull request by eapearson**
Includes work for  simpler widgets - how to, widget base object
Jim's vis widgets and sample panels moved to plugins
Code file re-org to simplify "active" codebase
Added browsers to testing ... maybe those should not be there to play well with auto tests

### CODE REVIEW

**Comment by briehl** [comment]
Yeah, Chrome doesn't work on Travis-CI, and Firefox needs a little additional configuration that isn't quite there yet. I think it's worth updating the Travis config, then putting the Chrome setup in either a separate config file, or as part of one of the Grunt tasks. That might not help your automatic Karma invocation as part of NetBeans, though.

**Comment by eapearson** [comment]
i'll remove the extra browsers (i see it isn't passing now) ... I can always even just have a separate karma config for netbeans

**Comment by briehl** [comment]
It might be a good idea to keep a local config for testing on a local machine, and a separate one for testing through the automated stuff. The environments should be nearly identical, but there's already a few differences, and those might grow.

**Comment by eapearson** [comment]
ok, so i'm using the testing config in test/dev and restored the other one to its previous state (I hope).

**Comment by briehl** [comment]
Great. Thanks!

**Pull request merged**
