### PR TITLE
First draft of ui plugin packages, fix to kbwidget adapter for params

### PR DESCRIPTION
**Pull request by eapearson**
Included is the first draft of "plugins", which are packages of javascript, css, configuration, and installation into the ui. Included are the conversion of several panels + widgets to plugins.
Also, a fix to the kbwidget adapter so that params provided to the "start" method are passed to the actual kbwidget during construction as "options".  The sample panel + widgets shows this, passing the query param 'param1' through the panel to the widget.

### CODE REVIEW

**Comment by briehl** [comment]
Looks good so far.
Should we be including the generated docs in the repo? Or have a webhook generate those and push them to gh-pages on pull? I think I'd prefer the latter - it makes PRs much easier to navigate, and we can just add a link to the docs in the readme.

**Comment by eapearson** [comment]
yes, the latter. I had hoped that the jsdocs pages would only be identical unless there was a change to the source, but it is not so, and there is way too much noise.

**Comment by eapearson** [comment]
btw I think a change for tomorrow will be that the plugin installation process will be declarative. right now it is driven by an installation module, which has the benefit of being very flexible, being able to modify the runtime in interesting ways, and good for prototyping, but not so **easy**. And, thinking ahead to a ui-tool for creating and managing plugins, configuration fits nicely into pushing buttons, selecting dropdowns, and filling out fields.

**Comment by eapearson** [comment]
it would be interesting to explore other solutions in this space. one obvious comparison is Wordpress. A small but functional core system, a rich api, great documentation, clunky as heck to build plugins, but the core product is simple, very stable, the plugin ecosystem thriving and diverse. The learning curve for wordpress plugin development does not seem to have hurt it. And they have not nearly solved all of the problems even with oceans of developer time.

**Comment by briehl** [comment]
Okay, is this ready for merge?

**Comment by eapearson** [comment]
Well, it works, so I don't see why not. We haven't really sat down to review whether it is a good design ... but if you are comfortable, I am.
Since then, there is a first plugin installed from github via bower.
And just moved (but not pushed yet, need more testing) the dataview panel into plugins. This means also a ton of data view widgets out of ui-common and into the dataview plugin. ui-common is shrinking...

**Comment by briehl** [comment]
Okay, let's merge and discuss tomorrow.

**Pull request merged**
